


public interface InitialsCounter {

    /**
     * Adds a person to your data structure.
     * @param person table of strings containing person data as generated by
     * the class RandomPersonGenerator.
     */
    void addPerson(String[] person);


    /**
     * Returns the number of times the given initials occur in the data.
     * Initials consist of the first character of every word of the first name
     * followed by the first character of every word of the last name.
     * There are no dots or spaces, e.g. "JVD" for "Jean-Claude Van Damme".
     *
     * @param initials the initials which should be counted
     * @return the number of people with the given initials.
     */
    int getNrOccurrences(String initials);

}
