/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.ArrayList;
import java.util.Collection;
import java.util.TreeSet;

/**
 *
 * @author tnaessens
 */
public class MyPhoneBookOud implements PhoneBook {

	/**
	 * Adds a person to your data structure.
	 * @param person table of strings containing person data as generated by
	 * the class RandomPersonGenerator.
	 */
	private TreeSet<NormalPerson> personen;
	private RandomPersonGenerator rpg;

	public MyPhoneBookOud() {
		rpg = RandomPersonGenerator.getInstance();
		rpg.setSeed(50);
		personen = new TreeSet<NormalPerson>();


		// Vult personen met een random lijst personen
		long tijd = System.currentTimeMillis();
		for (int i = 0; i < 500000; i++) {
			addPerson(rpg.getRandomPerson());
		}
		System.out.println(System.currentTimeMillis() - tijd);

	}

	public void addPerson(String[] person) {
		personen.add(new NormalPerson(person));
	}

	public Collection<String> getNumbers(String place, String lastName, String firstName) {
		Collection<String> nummers = new ArrayList();
		
		for (NormalPerson persoon : personen) {
			if (persoon.getGemeente().equals(place) && persoon.getNaam().equals(lastName) && persoon.getVoornaam().equals(firstName)) {
				nummers = persoon.getTelefoonnummer();
				break;
			}
		}
		return nummers;
	}

	public void addPhoneNumber(String place, String lastName, String firstName, String phoneNumber) {
		for (NormalPerson persoon : personen) {
			if (persoon.getGemeente().equals(place) && persoon.getNaam().equals(lastName) && persoon.getVoornaam().equals(firstName)) {
				persoon.addTelefoonnummer(phoneNumber);
				break;
			}
		}
	}

	public void write() {
		StringBuilder sb;

		for (NormalPerson persoon : personen) {
			sb = new StringBuilder();
			sb.append(persoon.getGemeente());
			sb.append(" ");
			sb.append(persoon.getNaam());
			sb.append(" ");
			sb.append(persoon.getVoornaam());
			for(String telnr : persoon.getTelefoonnummer()) {
				sb.append(" ");
				sb.append(telnr);
			}

			System.out.println(sb.toString());
		}

	}
}
