


import java.util.Collection;

public interface OldestPeopleFinder {

    /**
     * Adds a person to your data structure.
     * @param person table of strings containing person data as generated by
     * the class RandomPersonGenerator.
     */
    void addPerson(String[] person);

    /**
     * Finds the n oldest people in the given place.
     * Uses alphabetical order (first by last name, then by first name) in case of ties.
     * Returns a collection with the ID 's of the oldest people in the place,
     * in the required order.
     * If less than n people live in this place, simply return the ID 's of all
     * the inhabitants, in the required order.
     *
     * @param place the given place.
     * @param n desired number of people.
     * @return collection with ID 's of the oldest people.
     */
    Collection<String> findOldestPeople(String place, int n);

}
