


import java.util.Collection;

public interface PlaceFilter {

    /**
     * Adds a person to your data structure.
     * @param person table of strings containing person data as generated by
     * the class RandomPersonGenerator.
     */
    void addPerson(String[] person);

    /**
     * Removes all the inhabitants of the given city from your data structure.
     * Returns a collection of ID 's of the inhabitants which were removed from
     * the data structure.
     *
     * @param city city for which the inhabitants should be removed.
     * @return ID 's of the removed inhabitants.
     */
    Collection<String> removeInhabitants(String city);

}
